### ISSUE TITLE
[feature request] WAV output support.

### ISSUE THREAD

**Issue by avuton** [nschlia/ffmpegfs#1]
I would love to see [wav](https://en.wikipedia.org/wiki/WAV) support for this filesystem.

**Comment by nschlia** [comment]
Should be no big deal. I'll add it to the v1.1 feature list.

**Comment by nschlia** [comment]
WAV output added with https://github.com/nschlia/ffmpegfs/commit/719d282096a0409e93337ed74bc86d271c8a58c3

**Comment by avuton** [comment]
Thanks! 👍

**Comment by nschlia** [comment]
@avuton You're welcome.
