### ISSUE TITLE
Failed to create docker image from attached dockerfile

### ISSUE THREAD

**Issue by igor-epam** [nschlia/ffmpegfs#110]
Reading state information...
E: Unable to locate package libdvdread4
The command '/bin/sh -c apt-get install -yq libdvdread4 libdvdnav4 libbluray2' returned a non-zero code: 100

**Comment by nschlia** [comment]
Seems that the package has been renamed for Debian Bullseye, did not see that.
Try
`apt-get install libdvdread8 libdvdnav4 libbluray2` 
by editing the appropriate RUN line in your Dockerfiile.

I*ll add an updated file. Thanks for the hint.

**Comment by igor-epam** [comment]
Still doesn't work:
hecking for chardet >= 1.0.4... no
configure: error: Package requirements (chardet >= 1.0.4) were not met:

No package 'chardet' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables chardet_CFLAGS
and chardet_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
The command '/bin/sh -c ./configure' returned a non-zero code: 1

**Comment by nschlia** [comment]
Seems that even more things have changed... Hold on, I'll figure that out.

**Comment by igor-epam** [comment]
#111

**Comment by nschlia** [comment]
@igor-epam: You've basically made the same changes as I :) To credit your work I*ll merge the pull request, thanks for your help!

The problem was that after adding new dependencies to libchardet, I forgot to update the Dockerfile appropriately. Thanks again for pointing this out.

**Comment by igor-epam** [comment]
Thank you, cool.
Please enable actions, so next time someone breaks docker image creation PR fails.

**Comment by igor-epam** [comment]
The fix is not full.
There is runtime error of container:
 sudo docker logs ffmpegfs
/usr/local/bin/ffmpegfs: error while loading shared libraries: libchardet.so.1: cannot open shared object file: No such file or directory

**Comment by nschlia** [comment]
> error while loading shared libraries: libchardet.so.1: cannot open shared object file: No such file or directory

I think you specifically must add libchardet1, line 7 of Dockerfile should be:
`RUN apt-get install -yq fuse libfuse2 libsqlite3-0 libavcodec58 libavformat58 libswresample3 libavutil56 libswscale5 libavfilter7 libcue2 libchardet1`
I have successfully build the container and ran ffmpegfs in it. You can change your merge request accordingly.

**Comment by nschlia** [comment]
Now it*s perfect, I*ll merge the request.

Alas I get this error:
`/dst/                    : already mounted`
I am afraid I had this before, see issue #79. Seems that ffmpegfs does not detect that it is running under Docker.

**Comment by nschlia** [comment]
This one is fixed, the other problem see #79.

**Comment by igor-epam** [comment]
It looks like there is the reason of detection failure:
https://stackoverflow.com/questions/69002675/on-debian-11-bullseye-proc-self-cgroup-inside-a-docker-container-does-not-sho

**Comment by nschlia** [comment]
> It looks like there is the reason of detection failure:
Exactly, thanks for pointing me at it.

**Comment by nschlia** [comment]
> Thank you, cool. Please enable actions, so next time someone breaks docker image creation PR fails.

I'm not really a Docker crack, what would I have to do to "enable actions"?

**Comment by igor-epam** [comment]
> > Thank you, cool. Please enable actions, so next time someone breaks docker image creation PR fails.
> 
> I'm not really a Docker crack, what would I have to do to "enable actions"?

Everything works, docker build check is running. No action is needed.
