### ISSUE TITLE
Missing last track of each CD

### ISSUE THREAD

**Issue by Martin2112** [nschlia/ffmpegfs#122]
Hi,

I just built from the 2.9 release and while most things work I'm not seeing the last track on each CD. The CUE files were created by ExactAudioCopy.

I noticed in the Flac spec that there's expected to be a lead out track but if so these don't exist in the EAC files.

**Comment by nschlia** [comment]
Could you provide one or more problem cue sheet here? The cue sheets only, no audio files, of course.

**Comment by Martin2112** [comment]
OK. Here's one, it's fairly short.

```
REM DATE 1978
REM DISCID 18091C03
REM COMMENT "ExactAudioCopy v1.6"
PERFORMER "Tangerine Dream"
TITLE "Cyclone"
REM COMPOSER ""
FILE "Tangerine Dream - Cyclone.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Bent Cold Sidewalk"
    PERFORMER "Tangerine Dream"
    REM COMPOSER ""
    INDEX 00 00:00:00
    INDEX 01 00:00:10
  TRACK 02 AUDIO
    TITLE "Rising Runner Missed by Endless Sender"
    PERFORMER "Tangerine Dream"
    REM COMPOSER ""
    INDEX 00 13:06:67
    INDEX 01 13:11:35
  TRACK 03 AUDIO
    TITLE "Madrigal Meridian"
    PERFORMER "Tangerine Dream"
    REM COMPOSER ""
    INDEX 00 18:13:40
    INDEX 01 18:19:32
```

There should be 3 tracks but I see this:

```
ls /export/cdrip/flactrack/Tangerine\ Dream/Tangerine\ Dream\ -\ Cyclone.tracks
'01. Tangerine Dream - Bent Cold Sidewalk [13-06.760].mp4'
'02. Tangerine Dream - Rising Runner Missed by Endless Sender [05-02.066].mp4
```

**Comment by nschlia** [comment]
You are right, the last song is missing. I just checked another cue file I have, the last song is also missing...

I'll fix that ASAP.

Thanks for the bug report!

**Comment by Martin2112** [comment]
Thanks for the quick response.

**Comment by nschlia** [comment]
Fixed. This one was tricky, libcue reports no duration for the last track. This is because the information is not in the cuesheet file. This is why the file did not show up. I had to calculate the play time from the remaining duration of the input file.
