### ISSUE TITLE
Feature Request - Hide Files By Type or Regex

### ISSUE THREAD

**Issue by Martin2112** [nschlia/ffmpegfs#123]
Hi,

EAC creates 3 files per compressed image e.g X.flac, X.cue and X.jpg (cover image). It would be good to be able to hide some of these from the view created by ffmpegfs to make it less cluttered.

Could either be by regex or extension list and doesn't need to really complicated. e.g:

`--hide_extensions=jpg,png,cue` to stop covers and cue sheets from showing up.

**Comment by nschlia** [comment]
Should be easy. Added to the list :)

**Comment by nschlia** [comment]
> `--hide_extensions=jpg,png,cue` to stop covers and cue sheets from showing up.
Added as requested.
