### ISSUE TITLE
autocopy STRICT never triggers for video streams

### ISSUE THREAD

**Issue by mihaiush** [nschlia/ffmpegfs#151]
This condition 
https://github.com/nschlia/ffmpegfs/blob/b95ece1418c633378d47ccc69eef2c7c1efeab1b/src/ffmpeg_transcoder.cc#L811
always evaluates the audio codec regardless if the codec type is audio or video.
It always returns `false` for video streams.

**Comment by nschlia** [comment]
This is true, this is not the intended behaviour. I'll have to update that function. Thanks for pointing this out.

**Comment by mihaiush** [comment]
I have a patch, if you are interested I could make a MR.

**Comment by nschlia** [comment]
> I have a patch, if you are interested I could make a MR.

That would be cool, of course the patch is welcome.
