### ISSUE TITLE
prores cant allocate memory

### ISSUE THREAD

**Issue by zhuker** [nschlia/ffmpegfs#41]
branch: `release2.x` latest checkout

0. https://kote.videogorillas.com/vmir/ffmpegfs/Britney_Spears_Toxic.mov
1. `ffmpegfs --desttype=png -f -d /storage /ffmpegfs`
2. read pngs in 12 threads
3. get this in logs

```
   open[140693263617136] flags: 0x8000 /clients/downloads/brad_rushing/Britney_Spears_Toxic.mov/00000001292.png
   unique: 1700825, success, outsize: 32
unique: 1700826, opcode: READ (15), nodeid: 508, insize: 80, pid: 14060
read[140693263617136] 1 bytes from 0 flags: 0x8000
2019-09-23 13:12:45 ERROR  : [/ffmpegfs/Britney_Spears_Toxic.png] Reading image frame no. 1288: (12) Cannot allocate memory
   unique: 1700823, error: -12 (Cannot allocate memory), outsize: 16
unique: 1700827, opcode: READ (15), nodeid: 507, insize: 80, pid: 14056
read[140693263617136] 6 bytes from 0 flags: 0x8000
```

**Comment by nschlia** [comment]
Seems to be the old problem still, probably a synchronisation error. Happens on machine with many cores (>16). I'll try to figure out what's wrong ASAP.

**Comment by nschlia** [comment]
Error happened when the buffer grew beyond the starting size (60 KB) and decoding was restarted after a while. In that case the buffer was shrunk to these 60 KB, causing buffer access beyond these 60 KB to fail.

Should be fixed now :)
