### ISSUE TITLE
No way to specify number of channels (mono, stereo, etc)

### ISSUE THREAD

**Issue by VasylSamoilov** [nschlia/ffmpegfs#52]
There is no way to specify number of channels. In my use case I want to present mp3's as mono wav files. It would be nice to follow ffmpeg architecture and specify number of channels in general (1, 2, etc.)

**Comment by nschlia** [comment]
Yes, there is no command line parameter to set that. The transcoded file will always have 1 or 2 channels. 1 if the source is mono, 2 if the sources has 2 or more channels.

What about:

max_channels: limit to a max. number of channels, e.g. 2 will limit to stereo, unlimited will keep all channels (e.g. 5.1 surround) if supported by target format. Defaults to 2 channels.

So you may also create files with more than 2 channels. Not possible now.

I'll add that, easy to do. Please be a bit patient, I am currently migrating my SVN to GIT. Keeping me busy :)

**Comment by nschlia** [comment]
Added --audiochannels option to select a different number of channels. Defaults to 2 (stereo), may be set to 1 to create mono files. Set to 0 to keep the original number of channels.
