### ISSUE TITLE
is it me or nothing happens ?

### ISSUE THREAD

**Issue by Foul** [nschlia/ffmpegfs#55]
i cloned the git repo, installed all the dependancies, 

./autogen.sh
./configure
make 
make install

everything ok... i mount the filesystem : 
ffmpegfs --audiobitrate=256K --videobitrate=1.5M /mnt/BACKUP/Video/ /mnt/ffmpegfs -o allow_other,ro

![ffmpegfs](https://user-images.githubusercontent.com/829842/79219407-81e66700-7e52-11ea-9fa2-a06a6e263c2a.png)

but at the end... everything is the same in the 2 test directories...

**Comment by Foul** [comment]
Working perfect ! i just followed the exemple in the usage section ;)
You could add this "desttype=mp4" to it ;)

thx !

**Comment by nschlia** [comment]
> Working perfect ! i just followed the exemple in the usage section ;)
> You could add this "desttype=mp4" to it ;)

You're perfectly right. I was not aware of that, I'll add this right away.
