### ISSUE TITLE
m3u8 files not correctly detected

### ISSUE THREAD

**Issue by tg--** [nschlia/ffmpegfs#59]
If ffmpegfs comes acroess a m3u8 file (m3u playlist encoded in UTF-8), it tries to convert it to the target format - unsuccessfully of course.
This doesn't happen when the file ends on m3u instead of m3u8 (even the exact same file).

Input:
```
% ls
% echo "test" > test.m3u
% echo "test" > test.m3u8
% file *
test.m3u:  ASCII text
test.m3u8: ASCII text
```

Output:
```
% file *
test.m3u:      ASCII text
test.m3u8.mp3: cannot open `test.m3u8.mp3' (Bad file descriptor)
```

Mounted as follows:
```
ffmpegfs --audiobitrate=160K /home/thomasg/flac /home/thomasg/mp3 -o allow_other,ro,desttype=mp3

% mount
ffmpegfs on /home/thomasg/mp3 type fuse.ffmpegfs (ro,nosuid,nodev,relatime,user_id=1000,group_id=1000,allow_other)
```

**Comment by nschlia** [comment]
It should not open and try to convert that file in the first place. I'll check what happens.

Thanks for your report!

**Comment by nschlia** [comment]
You are right, m3u8 files were detected as "Apple HTTP Live Streaming" and thus FFmpegfs tried to transcode them. 

I've added the extension to the ignore list, now it works as expected.

**Comment by tg--** [comment]
Thanks for the quick fix, and thanks for ffmpegfs - it's a really cool tool, have been looking for a mp3fs-successor for a while, and this is clearly it!
Keep up the good work!

**Comment by nschlia** [comment]
Thanks. You're welcome - this was also an easy one to fix.
