### ISSUE TITLE
[Feature] Input m3u8, output mp4/mkv/ts

### ISSUE THREAD

**Issue by Emhc** [nschlia/ffmpegfs#84]
Hi, 

Thank you for this amazing app, I am just wondering if it is possible to have it "transcode" from m3u8 on the fly? Say I have a bunch of m3u8 files which are not live streams and would be updated daily by some python script, what I wish to achieve is to mount the output dir to plex and have ffmpegfs "transcode" (by transcode I mean download)  from the m3u8 when the it is being requested. Thanks in advance.

kind regards,
Eric

**Comment by nschlia** [comment]
That could be done, but would that not be a task for a bash, python, perl or whatever script? Simply mount the directory, parse the m3u files and copy all files to another directory?  Of course you should replace the extensions, and FFmpegfs will transode the files whilst copying.

**Comment by Emhc** [comment]
Thank you for getting back with me, I tried with python and bash before but couldn't even make it detectable to plex or emby. It sort of worked however it has the limitation you mentioned in the readme due to the time length is not provided. I guess I will have to live with that. Just wondering is there anyway to update the length dynamically if I output as ts? Both plex and emby take the time length of the buffered data at the time when the data was being called and will not update it's length.

Kind regards
Eric

**Comment by nschlia** [comment]
The length gets updated once the file was transcoded successfully. Simply do "cp path/to/ffmpegfsfile /dev/null" once so that file is fully transcoded. The size will be updated appropriately. Next time the file will come from cache real fast.

**Comment by nschlia** [comment]
Closed because won't implement. No a feature for FFmpegfs.
