### ISSUE TITLE
[FEATURE] Smart conversion option ("Smart Transcode") Audio/Video

### ISSUE THREAD

**Issue by nschlia** [nschlia/ffmpegfs#86]
Add a "Smart Transcode" option

- Convert audio-only files to WAV or AIFF
- Convert video-only and audio-video files to MOV

Smart transcoding currently simply determines the output format by taking the input format type into account, e.g., an MP3 would be recoded to AIFF, an MP4 to MOV even if the input MP4 does not contain a video stream.

The input format should be scanned for streams and the output selected appropriately: An MP4 with video should be transcoded to MOV, an MP4 with audio only to AIFF.

**Comment by felixbecker2** [comment]
Would this also solve the fact that when `--desttype=MP3+WEBM` or `--desttype=MP3+MP4`, all audio files get transcoded to WebM or MP4?

It would be nice if some transcoding-mappings could also be specified manually by from-to-pairs, e.g. `--mapping=<mimetype>:<format>` (multiple options possible).

**Comment by nschlia** [comment]
> Would this also solve the fact that when `--desttype=MP3+WEBM` or `--desttype=MP3+MP4`, all audio files get transcoded to WebM or MP4?

This would recode audio formats to MP3 and video files to WebM or MP4. Audio only formats will never be recoded to WebM or MP4 in these cases.  BTW, `--desttype=MP3+MP4` would not make much sense as MP4 can perfectly contain audio only. 

Currently the decision whether to target MP3 or WebM is done by the capabilities of the input format - e.g. WAV or AIFF gets recoded to MP3. AVI or MP4 to WebM, even if the source does not contain video. This is quite dumb.

The enhancement planned would be that a check is added so that a video capable format that  contains no video will be transcoded to MP3.

As now the files are checked first for cue sheets the necessary information should be available now. I*ll see if I can implement the feature now,

> It would be nice if some transcoding-mappings could also be specified manually by from-to-pairs, e.g. `--mapping=<mimetype>:<format>` (multiple options possible)

Probably this could be done, but what would be the use case for this?

**Comment by felixbecker2** [comment]
> > Would this also solve the fact that when `--desttype=MP3+WEBM` or
> > `--desttype=MP3+MP4`, all audio files get transcoded to WebM or
> > MP4?  
> 
> This would recode audio formats to MP3 and video files to WebM or
> MP4.

I observe differently: This encodes all audio for me to mp4 or webm!

> Audio only formats will never be recoded to WebM or MP4 in these
> cases.  BTW, `--desttype=MP3+MP4` would not make much sense as MP4
> can perfectly contain audio only. 

My use case is a transcoding backend for
[`minidlnad`](https://sourceforge.net/projects/minidlna/) and I want to
provide one place, where I have all audio as mp3 and all video as mp4
or webm (still not decided). I have an audio only player that only eats
mp3 (and not mp4), for this it is mp3; and for video players on the
network mp4 or webm will be offered.


> Currently the decision whether to target MP3 or WebM is done by the
> capabilities of the input format - e.g. WAV or AIFF gets recoded to
> MP3. AVI or MP4 to WebM, even if the source does not contain video.
> This is quite dumb.

OK, I mount with `--desttype=MP3+MP4` and see

* `.aac` files as `.aac.mp4` (yes, I have "plain" .aac audio files),
* `.ogg` audio files as `.ogg.mp4`,
* `.mp3` audio files as `.mp3.mp4`.

With `--desttype=MP3+WEBM` I get `.webm`-files from the above.

Complete command line:  
`ffmpegfs -o allow_other,ro --max_threads=1 --desttype=MP3+WEBM --autocopy=MATCH --profile=FF --level=STANDARD --hwaccel_enc=VAAPI --hwaccel_dec=VAAPI -f -d /home/[...]/music /mnt/ffmpegfs/music/`

`ffmpegfs --version`:

```
Built with          : gcc 11.1.0 (linux-gnu)
configuration       : --prefix=/usr

FFMPEGFS Version    : 2.6
FFmpeg Version      : n4.4
Video CD Library    : enabled
DVD Library         : enabled
Bluray Library      : 1.3.0
FUSE library version: 2.9.9
fusermount version: 2.9.9
using FUSE kernel interface version 7.19
```


> > It would be nice if some transcoding-mappings could also be
> > specified manually by from-to-pairs, e.g.
> > `--mapping=<mimetype>:<format>` (multiple options possible)  
> 
> Probably this could be done, but what would be the use case for this? 

You could e.g. transcode (lossless) flac to (lossless) wav but your low-quality .ogg-collection can become mp3.

I know that [`gerbera`](https://github.com/gerbera/gerbera) has this mapping possibilities to adapt to different media players on the network.


-- 
Erleuchtung, die:
  Wenn Du plötzlich merkst, dass Du sie gar nicht brauchst.
  (Janosch.)

Enlightenment:
  When you suddenly realise that you do not need it.
  (Janosch.)

**Comment by nschlia** [comment]
Think that should be possible now. The problem was, the input file must be scanned first to detect video tracks. At the time I implemented this feature this was not done. But now the files get scanned for cue sheets and thus I have the information required.
