### ISSUE TITLE
[FEATURE] allow specification of destination type for audio, video _and_ picture (i.e. three types).

### ISSUE THREAD

**Issue by felixbecker2** [nschlia/ffmpegfs#95]
Currently, the `--desttype` parameter accepts only two options.

But when there is a folder with audio, video _and_ pictures, it would need three options, like `--desttype=MP3+JPG+WEBM`.

`--desttype=MP3+JPG+WEBM` fails for me with error message

```
INVALID PARAMETER: Missing destination type string
INVALID PARAMETER: Parsing options.
```

(I am using ffmpegfs version 2.6.)

**Comment by nschlia** [comment]
FFmpegfs supports no picture files as input, video or audio only.

What do you have in mind with a JPG or PNG input file?

**Comment by felixbecker2** [comment]
> FFmpegfs supports no picture files as input, video or audio only.

Ah OK, makes sense.

> What do you have in mind with a JPG or PNG input file?

I am using ffmpegfs as a backend for [`minidlnad`](https://sourceforge.net/projects/minidlna/), and just assumed it also can convert between still image formats. It was a shortcut assumption I got when I read about still image as output mode. And "consumer grade" technology usually only understands jpeg, png and maybe gif and a few others, but probably not avif for example.

So I think this feature request is obsolete, please close it as inappropriate.


-- 
Planung ist der Ersatz des Zufalls durch den Irrtum.

**Comment by nschlia** [comment]
I see. I never thought about still images as input. Seems that FFmpeg supports several of these formats, I*ll add the request to the list. Seems like a useful idea to  convert e.g.  XBM, TIFF or PCX to PNG or so.

**Comment by felixbecker2** [comment]
*(Just a sidenote: I thing [GraphicsMagick](http://www.graphicsmagick.org/)/ [ImageMagick](https://www.imagemagick.org/) are the better backends for still image converstion, so maybe indeed no support in FFmpegfs but rather a new graphicsmagickfs would be interesting here?)*

**Comment by nschlia** [comment]
> _(Just a sidenote: I think [GraphicsMagick](http://www.graphicsmagick.org/)/ [ImageMagick](https://www.imagemagick.org/) are the better backends than FFmpeg for still image converstion, so maybe indeed no support in FFmpegfs but rather a new graphicsmagickfs would be interesting here?)_

You are right, so I will close this.
