### ISSUE TITLE
All audio files are converted to "video" format if `--desttype` contains `MP3+WEBM` or `MP3+MP4`.

### ISSUE THREAD

**Issue by felixbecker2** [nschlia/ffmpegfs#99]
*This is a follow up from [&rarr; here (issue #86)](/nschlia/ffmpegfs/issues/86#issuecomment-960286269):*

## What I do:

I mount a directory containing music files with `ffmpegfs` as follows:

```
ffmpegfs -o allow_other,ro --max_threads=1 --desttype=MP3+WEBM --autocopy=MATCH --profile=FF --level=STANDARD --hwaccel_enc=VAAPI --hwaccel_dec=VAAPI -f -d /home/music /mnt/ffmpegfs/music/
```

In that directory I have audio files in the formats OGG/Vorbis, mp3, AAC (without container), and some others.

## Problem:

I observe that all the audio files get converted to WebM, and not MP3; even preexisting MP3 get converted to WebM.

## Expected behaviour:

Convert at least file formats which are known to be audio only (`.mp3`, `.wav`, `.flac`) to MP3.

#### Original files:

1. `sounds/letter_in_mailbox.ogg`
2. `sounds/water.mp3`
3. `sounds/silence/flac/silence-010s.flac`
4. `sounds/silence/flac/silence-060s.wav`
5. `Hannes_Wader/Der_Rattenfaenger/01_-_Der_Rattenfaenger.aac`
6. `Klassik/Bedrich_Smetana/Smetana_-_Vltava.mp4`

#### Files in `ffmpegfs` mount:

1. `sounds/letter_in_mailbox.ogg.webm`
2. `sounds/water.mp3.webm`
3. `sounds/silence/flac/silence-010s.flac.webm`
4. `sounds/silence/flac/silence-060s.wav.webm`
5. `Hannes_Wader/Der_Rattenfaenger/01_-_Der_Rattenfaenger.aac.webm`
6. `Klassik/Bedrich_Smetana/Smetana_-_Vltava.mp4.webm`

##### Original file:

* `mediainfo sounds/letter_in_mailbox.ogg`:  
  ```
  General
  Complete name                            : sounds/letter_in_mailbox.ogg
  Format                                   : Ogg
  File size                                : 12.5 KiB
  Duration                                 : 2 s 404 ms
  Overall bit rate mode                    : Variable
  Overall bit rate                         : 42.5 kb/s
  Comment                                  : File created by GoldWave.  GoldWave copyright (C) Chris Craig

  Audio
  ID                                       : 1804289383 (0x6B8B4567)
  Format                                   : Vorbis
  Duration                                 : 2 s 404 ms
  Bit rate mode                            : Variable
  Bit rate                                 : 29.0 kb/s
  Channel(s)                               : 1 channel
  Sampling rate                            : 11.025 kHz
  Compression mode                         : Lossy
  Stream size                              : 8.51 KiB (68%)
  Writing library                          : libVorbis 1.0.1 (UTC 2003-09-09)
  ```

* `ffprobe sounds/letter_in_mailbox.ogg`:  
  ```
  ffprobe version n4.4 Copyright (c) 2007-2021 the FFmpeg developers
    built with gcc 11.1.0 (GCC)
    configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
    libavutil      56. 70.100 / 56. 70.100
    libavcodec     58.134.100 / 58.134.100
    libavformat    58. 76.100 / 58. 76.100
    libavdevice    58. 13.100 / 58. 13.100
    libavfilter     7.110.100 /  7.110.100
    libswscale      5.  9.100 /  5.  9.100
    libswresample   3.  9.100 /  3.  9.100
    libpostproc    55.  9.100 / 55.  9.100
  Input #0, ogg, from 'sounds/letter_in_mailbox.ogg':
    Duration: 00:00:02.40, start: 0.000000, bitrate: 42 kb/s
    Stream #0:0: Audio: vorbis, 11025 Hz, mono, fltp, 29 kb/s
      Metadata:
        COMMENT         : File created by GoldWave.  GoldWave copyright (C) Chris Craig
                        : 
  ```

##### File in `ffmpegfs` mount:

* \[[&rarr; Here](https://github.com/nschlia/ffmpegfs/files/7476681/ffmpegfs-transcode-ogg-to-webm.log)\] I have attached the terminal output of a run of `ffmpegfs -o allow_other,ro --max_threads=1 --desttype=MP3+WEBM --autocopy=MATCH --profile=FF --level=STANDARD --hwaccel_enc=VAAPI --hwaccel_dec=VAAPI -f -d /home/music /mnt/ffmpegfs/music/` after complete deletion of `ffmpegfs`'s cache with a read of `sounds/letter_in_mailbox.ogg.webm` (`dd if=sounds/letter_in_mailbox.ogg.webm of=/dev/zero`).

* `mediainfo sounds/letter_in_mailbox.ogg.webm`:  
  ```
  General
  Complete name                            : sounds/letter_in_mailbox.ogg.webm
  Format                                   : WebM
  Format version                           : Version 4
  File size                                : 10.8 KiB
  Duration                                 : 2 s 404 ms
  Overall bit rate                         : 36.8 kb/s
  Writing application                      : Lavf58.76.100
  Writing library                          : Lavf58.76.100
  Comment                                  : File created by GoldWave.  GoldWave copyright (C) Chris Craig
  IsTruncated                              : Yes

  Audio
  ID                                       : 1
  Format                                   : Opus
  Codec ID                                 : A_OPUS
  Duration                                 : 2 s 404 ms
  Channel(s)                               : 1 channel
  Channel layout                           : C
  Sampling rate                            : 12.0 kHz
  Bit depth                                : 32 bits
  Compression mode                         : Lossy
  Default                                  : Yes
  Forced                                   : No
  Comment                                  : File created by GoldWave.  GoldWave copyright (C) Chris Craig
  ```

* `ffprobe sounds/letter_in_mailbox.ogg.webm`:  
  ```
  ffprobe version n4.4 Copyright (c) 2007-2021 the FFmpeg developers
    built with gcc 11.1.0 (GCC)
    configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
    libavutil      56. 70.100 / 56. 70.100
    libavcodec     58.134.100 / 58.134.100
    libavformat    58. 76.100 / 58. 76.100
    libavdevice    58. 13.100 / 58. 13.100
    libavfilter     7.110.100 /  7.110.100
    libswscale      5.  9.100 /  5.  9.100
    libswresample   3.  9.100 /  3.  9.100
    libpostproc    55.  9.100 / 55.  9.100
  Input #0, matroska,webm, from 'sounds/letter_in_mailbox.ogg.webm':
    Metadata:
      COMMENT         : File created by GoldWave.  GoldWave copyright (C) Chris Craig
                      : 
      ENCODER         : Lavf58.76.100
    Duration: 00:00:02.40, start: -0.002000, bitrate: 36 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, mono, fltp (default)
      Metadata:
        COMMENT         : File created by GoldWave.  GoldWave copyright (C) Chris Craig
                        : 
  ```

## Further remarks:

* Similar if I change `WEBM` to `MP4` in the destination format specification: Then it converts all to `MP4`.
* Note that the `.flac.webm` and `.wav.webm` files could not be played back at all (while the original files work). They _do_ work if I change target format `WEBM` to `MP4` _and_ remove the `--autocopy`.
* Removing `--autocopy` does still convert the audio files to WebM or MP4.

## Software version:

* `ffmpegfs --version`:  
  ```
  -------------------------------------------------------------------------------------------
  Built with          : gcc 11.1.0 (linux-gnu)
  configuration       : --prefix=/usr --disable-debug --with-libswresample --with-libavresample --with-libdvd --with-libbluray --with-libvcd --with-extra-version=git20211031.8bf2856f

  FFMPEGFS Version    : 2.7-git20211031.8bf2856f
  FFmpeg Version      : n4.4
  Video CD Library    : enabled
  DVD Library         : enabled
  Bluray Library      : 1.3.0
  FUSE library version: 2.9.9
  fusermount version: 2.9.9
  using FUSE kernel interface version 7.19
  ```

**Comment by nschlia** [comment]
This is not a bug, the correct format would be `--desttype=WEBM+MP3` or `--desttype=MP4+MP3`, the video format must be specified first.

For example, with `--desttype=WEBM+MP3` all MP3/WAV files are converted to MP3, and MP4 to WebM, as expected.

I'll add a check, if an audio only format is specified first, the command line will be rejected with an error message.

**Comment by felixbecker2** [comment]
On Fri, 05 Nov 2021 11:29:50 +0000 (UTC), Norbert Schlia
***@***.***> wrote about "Re: [nschlia/ffmpegfs] All
audio files are converted to "video" format if `--desttype` contains
`MP3+WEBM` or `MP3+MP4`. (Issue #99)":

> This is not a bug, the correct format would be `--desttype=WEBM+MP3`
> or `--desttype=MP4+MP3`, the video format must be specified first.

Thanks, that explains thinks and now it works as expected.

OGG files get converted to videos, maybe because it is a container that might contain video at all.

(`file sounds/letter_in_mailbox.ogg` says  
`sounds/letter_in_mailbox.ogg: Ogg data, Vorbis audio, mono, 11025 Hz, ~29000 bps, created by: Xiph.Org libVorbis I (1.0.1)`  
though, so it looks like that already at that point can be determined that there is only audio, but I think this will be tackled by issue #86.)

Thanks for the clarification, and

> I'll add a check, if an audio only format is specified first, the command line will be rejected with an error message.

thanks for the wrong-input handling!



-- 
Machen ist wie wollen, nur krasser.

**Comment by nschlia** [comment]
> OGG files get converted to videos, maybe because it is a container that might contain video at all.

Yep. OGG is video capable. FFmpegfs handles the formats quit dumb. For example, using using `--desttype=WEBM+MP3`: MP3, AIFF, WAV - make MP3s. WebM, AVI, MP4, OGG - make WebM.

I'll enhance that as with issue #86.

> Thanks for the clarification, and thanks for the wrong-input handling!

You're welcome!
